### ISSUE TITLE
Missing Enum for JUSTIFY

### ISSUE THREAD

**Issue by drmacro** [drmacro/wordinator#14]
A <td align="justify"> causes a crash with the following error:

[java] java.lang.IllegalArgumentException: No enum constant org.apache.poi.xwpf.usermodel.ParagraphAlignment.JUSTIFY
[java]     at java.lang.Enum.valueOf(Enum.java:238)
[java]     at org.apache.poi.xwpf.usermodel.ParagraphAlignment.valueOf(ParagraphAlignment.java:29)
[java]     at org.wordinator.xml2docx.generator.DocxGenerator.makeTableRow(DocxGenerator.java:2045)
[java]     at org.wordinator.xml2docx.generator.DocxGenerator.makeTable(DocxGenerator.java:1552)
[java]     at org.wordinator.xml2docx.generator.DocxGenerator.handleBody(DocxGenerator.java:372)
[java]     at org.wordinator.xml2docx.generator.DocxGenerator.handleSection(DocxGenerator.java:416)
[java]     at org.wordinator.xml2docx.generator.DocxGenerator.handleBody(DocxGenerator.java:369)
[java]     at org.wordinator.xml2docx.generator.DocxGenerator.constructDoc(DocxGenerator.java:339)
[java]     at org.wordinator.xml2docx.generator.DocxGenerator.generate(DocxGenerator.java:312)
[java]     at org.wordinator.xml2docx.MakeDocx.handleSingleSwpxDoc(MakeDocx.java:272)
[java]     at org.wordinator.xml2docx.MakeDocx.handleDirectory(MakeDocx.java:294)
[java]     at org.wordinator.xml2docx.MakeDocx.handleCommandLine(MakeDocx.java:163)
[java]     at org.wordinator.xml2docx.MakeDocx.main(MakeDocx.java:69)
[java] + 2019-08-21 14:39:02,053 [ERROR] Unexpected IllegalArgumentException: No enum constant org.apache.poi.xwpf.usermodel.ParagraphAlignment.JUSTIFY

According to the rng "justify" is a valid value for align attribute on a <td>. There must be a constants mismatch of some kind.

**Comment by drmacro** [comment]
Duplicate--already fixed
