### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by gkholman** [drmacro/wordinator#82]
My SWPX file passes the schema, yet I get the following:
```
     [java] java.lang.StringIndexOutOfBoundsException: begin 0, end -2, length 0
     [java] 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
     [java] 	at java.base/java.lang.String.substring(String.java:1874)
     [java] 	at org.wordinator.xml2docx.generator.Measurement.toInches(Measurement.java:63)
     [java] 	at org.wordinator.xml2docx.generator.Measurement.toPixels(Measurement.java:27)
     [java] 	at org.wordinator.xml2docx.generator.DocxGenerator.makeImage(DocxGenerator.java:1961)
     [java] 	at org.wordinator.xml2docx.generator.DocxGenerator.makeParagraph(DocxGenerator.java:1313)
     [java] 	at org.wordinator.xml2docx.generator.DocxGenerator.makeParagraph(DocxGenerator.java:1208)
     [java] 	at org.wordinator.xml2docx.generator.DocxGenerator.handleBody(DocxGenerator.java:478)
     [java] 	at org.wordinator.xml2docx.generator.DocxGenerator.constructDoc(DocxGenerator.java:435)
     [java] 	at org.wordinator.xml2docx.generator.DocxGenerator.generate(DocxGenerator.java:417)
     [java] 	at org.wordinator.xml2docx.MakeDocx.handleSingleSwpxDoc(MakeDocx.java:331)
     [java] 	at org.wordinator.xml2docx.MakeDocx.handleDirectory(MakeDocx.java:353)
     [java] 	at org.wordinator.xml2docx.MakeDocx.handleCommandLine(MakeDocx.java:199)
     [java] 	at org.wordinator.xml2docx.MakeDocx.main(MakeDocx.java:86)
```

File sent separately by email. Reproducible this time!!

**Comment by gkholman** [comment]
I've narrowed this down to an empty width="" attribute on <wp:image>.

When I prevent this from being added, the DOCX is generated.

**Comment by drmacro** [comment]
I'll update the code to catch this case.
